version: "3.8"

services:
  backend:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    networks:
      - app_network
  frontend:
    build: ./irony-service-agent-ui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app_network
    depends_on:
      - backend
networks:
  app_network:
    driver: bridge
