services:
  backend:
    build: ./irony_backend
    container_name: irony_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # networks:
    #   - app_network
  frontend:
    build:
      context: ./irony-service-agent-ui
      args:
        NEXT_PUBLIC_API_URL: "http://backend:8000"
        NEXT_PUBLIC_CLIENT_API_URL: "https://irony.store"
    container_name: irony_frontend
    ports:
      - "3000:3000"

    depends_on:
      - backend

    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_CLIENT_API_URL=https://irony.store

    restart: unless-stopped
    # networks:
    #   - app_network
# networks:
#   app_network:
#     driver: bridge
