services:
  redis:
    image: redis
    container_name: irony_redis_prod
    ports:
      - "6380:6379"
    restart: unless-stopped

  backend:
    build: ./irony_backend
    image: irony_backend_prod  # <--- Add this line
    container_name: irony_backend_prod
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: ./irony-service-agent-ui
    image: irony_frontend_prod  # <--- Add this line
    container_name: irony_frontend_prod
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - TZ=Asia/Kolkata
    restart: unless-stopped
